(() => {
  const mediaBase = window.resolveMediaUrl ? window.resolveMediaUrl('assets') : 'assets';
  const total=8,step=40,box=document.querySelector('#bag-spinner'),img=document.querySelector('#bag-image'),note=document.querySelector('#bag-fallback');
  if(!box||!img)return;let frame=0,lastX=0,down=false;const frames=Array.from({length:total},(_,i)=>'assets/bag/angle-'+String(i+1).padStart(2,'0')+'.png');const ready=new Set();
  const title=document.querySelector('.bag-section h1');if(title)title.textContent='BRINE喵系古早卡通印花杜邦纸包';
  const decorStyle=document.createElement('style');decorStyle.textContent='.bag-shape{position:fixed;z-index:0;width:min(230px,23vw);pointer-events:none;opacity:.22;mix-blend-mode:screen}.bag-shape-a{left:2vw;top:28vh}.bag-shape-b{right:2vw;bottom:13vh;transform:rotate(12deg)}@media(max-width:760px){.bag-shape{width:135px;opacity:.14}.bag-shape-a{left:-35px;top:24vh}.bag-shape-b{right:-35px;bottom:14vh}}';document.head.append(decorStyle);
  const shapeA=document.createElement('img'),shapeB=document.createElement('img');shapeA.className='bag-shape bag-shape-a';shapeB.className='bag-shape bag-shape-b';shapeA.src='assets/bag/media/shape-222.png';shapeB.src='assets/bag/media/shape-333.png';shapeA.alt=shapeB.alt='';document.body.prepend(shapeA,shapeB);
  const mediaStyle=document.createElement('style');mediaStyle.textContent='.laptop-showcase{width:min(700px,100%);margin:0 auto 38px}.laptop-wrap{position:relative;width:100%;filter:drop-shadow(0 18px 26px rgba(79,209,165,.22))}.laptop-shell{position:relative;z-index:2;display:block;width:100%;pointer-events:none}.screen-wrap{position:absolute;z-index:1;left:14%;top:12%;width:72%;height:76%;overflow:hidden;border:1px solid rgba(168,255,216,.3);border-radius:10px;box-shadow:inset 0 0 14px rgba(0,0,0,.45)}.screen-wrap video{width:100%;height:100%;object-fit:cover;cursor:pointer}.video-hint{position:absolute;inset:0;display:grid;place-items:center;color:#a8ffd8;font-size:30px;opacity:0;transition:opacity .2s;background:rgba(13,31,26,.22);pointer-events:none}.screen-wrap:hover .video-hint{opacity:1}.video-toggle{position:absolute;z-index:3;right:2%;bottom:7%;width:38px;height:38px;border:1px solid rgba(168,255,216,.45);border-radius:50%;background:rgba(13,31,26,.7);color:#a8ffd8;cursor:pointer}.media-fallback{position:absolute;z-index:4;inset:0;display:grid;place-items:center;color:#ffb3c6}@media(max-width:600px){.laptop-showcase{margin-bottom:24px}.video-toggle{width:32px;height:32px;font-size:12px}}';document.head.append(mediaStyle);
  const layerFix=document.createElement('style');layerFix.textContent='.screen-wrap{z-index:4!important;left:15%!important;top:19%!important;width:70%!important;height:45%!important}.video-toggle{z-index:5!important}.media-fallback{z-index:6!important}';document.head.append(layerFix);
  const showcase=document.createElement('section');showcase.className='laptop-showcase';showcase.innerHTML='<div class="laptop-wrap"><div class="screen-wrap"><video muted loop playsinline preload="metadata" src="'+mediaBase+'/bag/media/product.mp4"></video><span class="video-hint">▶</span></div><img class="laptop-shell" src="'+mediaBase+'/bag/media/laptop.png" alt="电脑屏幕展示产品视频"><span class="media-fallback" hidden>产品视频或电脑外壳无法加载</span><button type="button" class="video-toggle" aria-label="暂停视频">❚❚</button></div>';
  const main=document.querySelector('.sub-main');main.insertBefore(showcase,main.firstChild);const video=showcase.querySelector('video'),toggleButton=showcase.querySelector('.video-toggle'),fail=showcase.querySelector('.media-fallback'),shell=showcase.querySelector('.laptop-shell');fail.remove();
  video.play().catch(()=>{});const toggleVideo=()=>{if(video.paused){video.play().catch(()=>{});toggleButton.textContent='❚❚';toggleButton.setAttribute('aria-label','暂停视频')}else{video.pause();toggleButton.textContent='▶';toggleButton.setAttribute('aria-label','播放视频')}};video.onclick=toggleVideo;toggleButton.onclick=toggleVideo;shell.onerror=()=>{};
  const details=document.querySelector('.bag-details');if(details)details.hidden=true;
  box.style.background='transparent';box.style.border='0';box.style.overflow='visible';
  const doily=document.createElement('img');doily.className='lace-doily';doily.src='assets/images/lace-doily.png';doily.alt='';doily.style.cssText='position:absolute;z-index:0;width:82%;height:82%;object-fit:contain;opacity:.96;pointer-events:none';
  box.insertBefore(doily,img);img.style.position='relative';img.style.zIndex='1';
  const gallery=document.createElement('section');gallery.className='bag-detail-gallery';gallery.setAttribute('aria-label','包包商品详情');gallery.style.cssText='width:min(760px,100%);margin:52px auto 0;line-height:0';
  for(let i=1;i<=10;i++){const detail=document.createElement('img');detail.src='assets/bag/details/'+i+'.jpg';detail.alt='薄荷月光包商品详情图 '+i;detail.loading=i>2?'lazy':'eager';detail.style.cssText='display:block;width:100%;height:auto;margin:0';detail.onerror=()=>detail.remove();gallery.append(detail)}
  document.querySelector('.bag-section').append(gallery);
  const bottomDecor=document.createElement('div');bottomDecor.style.cssText='display:flex;align-items:center;justify-content:center;gap:22px;max-width:560px;margin:34px auto 20px;padding:14px;overflow:hidden';
  ['shape-222.png','shape-333.png'].forEach((name,i)=>{const mark=document.createElement('img');mark.src='assets/bag/media/'+name;mark.alt='';mark.style.cssText='display:block;width:'+(i===0?'58%':'32%')+';height:auto;opacity:.75;mix-blend-mode:screen';bottomDecor.append(mark)});
  document.querySelector('.bag-section').append(bottomDecor);
  frames.forEach(src=>{const p=new Image();p.onload=()=>ready.add(src);p.onerror=()=>console.warn('无法加载序列图：'+src);p.src=src});
  const show=n=>{frame=(n%total+total)%total;const src=frames[frame];img.src=src;img.alt='薄荷月光包，第 '+(frame+1)+' 个角度'};
  box.onpointerdown=e=>{down=true;lastX=e.clientX;box.classList.add('is-dragging');box.setPointerCapture(e.pointerId)};
  box.onpointermove=e=>{if(!down)return;const n=Math.trunc((e.clientX-lastX)/step);if(n){show(frame+n);lastX+=n*step}};
  box.onpointerup=box.onpointercancel=()=>{down=false;box.classList.remove('is-dragging')};img.onerror=()=>note.hidden=false;setTimeout(()=>{if(!ready.size)note.hidden=false},1200);
})();
